services:
  db:
    image: postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password123
    ports:
      - 5432:5432

volumes:
  pgdata:
