# Run with: `docker-compose -f docker-compose.dev.yml up -d`
services:
    db:
        image: postgres
        restart: always
        volumes:
            - pgdata:/var/lib/postgresql
        environment:
            POSTGRES_PASSWORD: password123
        ports:
            - 5432:5432
        networks:
            - internal-dev

    poll-worker:
        build:
            context: .
            dockerfile: Dockerfile-Worker.dev
            args:
                - ARG_DATABASE_URL=$DATABASE_URL
        container_name: docker-poll-worker
        env_file: workers/poll-worker/.env
        networks:
            - internal-dev
        restart: always


volumes:
    pgdata:

networks:
    internal-dev:
        driver: bridge
