name: Cypress Component Tests

on:
    push:
        paths-ignore:
            - docs/**
            - '**/*.md'
jobs:
    setup:
        name: Set up environments
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v4
            -   uses: actions/setup-node@v3
                with:
                    node-version: '18.18.0'
            -   name: Install dependencies
                run: npm ci
            -   name: Write environment variables
                run: |
                    echo "${{ secrets.ENV_TEST_LOCAL }}" > .env
                    echo "" > cypress.config.json

    lint:
        name: Run Lint and Prettier
        runs-on: ubuntu-latest
        needs: [ setup ]
        steps:
            -   name: ESLint
                run: npm run lint
            -   name: Prettier
                run: npx prettier . --check

    cypress-component:
        name: Run cypress component tests
        runs-on: ubuntu-latest
        needs: [ setup, lint ]
        steps:
            -   name: Cypress Run Component Tests
                uses: cypress-io/github-action@v6
                env:
                    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                    GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
                with:
                    install: false
                    browser: chrome
                    component: true
