name: Cypress E2E Tests (Preview Deployment)

on:
    workflow_dispatch:
        inputs:
            run_deploy:
                description: 'Run deploy-preview job'
                required: false
                type: boolean
                default: false

jobs:
    deploy-preview:
        name: Deploy Preview
        runs-on: ubuntu-latest
        if: ${{ inputs.run_deploy }}
        env:
            VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
            VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        steps:
            -   uses: actions/checkout@v4
            -   name: Install Vercel CLI
                run: npm install --global vercel@latest
            -   name: Pull Vercel Environment Information
                run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
            -   name: Write .env
                run: |
                    echo "${{ secrets.ENV_PREVIEW }}" > .env
            -   name: Build Project Artifacts
                run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
            -   name: Deploy Project Artifacts to Vercel
                run: |
                    url="$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }})"
                    vercel alias --token=${{ secrets.VERCEL_TOKEN }} set "$url" ubco-capstone-team-3.vercel.app

    setup-db:
        name: Set up database
        runs-on: ubuntu-latest
        if: ${{ inputs.run_deploy }}
        needs: [ 'deploy-preview' ]
        steps:
            -   uses: actions/checkout@v4
            -   name: Write environment variables
                run: |
                    echo "${{ secrets.ENV_PREVIEW }}" > .env
            -   name: Migrate Database
                run: npx prisma migrate dev &> prisma_migrate.log



    cypress-e2e:
        name: Run cypress E2E tests on preview deployment
        runs-on: ubuntu-latest
        if: always()
        needs: [ deploy-preview, setup-db ]
        steps:
            -   uses: actions/checkout@v4
            -   name: Write environment variables
                run: |
                    echo "${{ secrets.ENV_PREVIEW }}" > .env
#            -   name: Cypress Run E2E Tests
#                id: cypress-run
#                uses: cypress-io/github-action@v6
#                env:
#                    CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
#                    GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
#                with:
#                    wait-on: ${{ secrets.CYPRESS_BASE_URL }}
#                    browser: chrome
#                    record: true
#                    config: baseUrl=${{ secrets.CYPRESS_BASE_URL }}
#                    group: 'E2E Tests on Preview workflow'
            -   uses: jwalton/gh-find-current-pr@v1
                id: findPr
                env:
                    GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
            -   name: Report test result to Pull Request
                if: always()
#                run: |
#                  gh api --method POST \
#                  -H "Accept: application/vnd.github+json" \
#                  "/repos/COSC-499-W2023/year-long-project-team-3/$PULL_REQUEST_NUMBER/comments" \
#                  -f body='#### Cypress Tests: ${{ steps.cypress-run.outcome }}. See results at ${{ steps.cypress-run.outputs.dashboardUrl }}' \
#                  -f event='COMMENT'
                run: |
                    run: echo "===============> Version from $GITHUB_REF"
                env:
                    GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
                    PULL_REQUEST_NUMBER: ${{ steps.findPr.outputs.pr }}