name: Lint

on: push

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v3
              with:
                  node-version: '18.18.0'
            - run: npm ci
            - name: ESLint
              run: npm run lint
            - name: Prettier
              run: npx prettier . --check
