name: Cypress Tests

on:
    push:
        branches-ignore:
            - main
jobs:
    cypress-run:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                containers: [1, 2] # Uses 2 parallel instances
        steps:
            - name: Get the run id of vercel preview deployment
              uses: codex-/return-dispatch@v1
              id: return_dispatch
              with:
                token: ${{ github.token }}
                repo: year-long-project-team-3
                owner: COSC-499-W2023
                workflow: vercel_preview_deployment.yml
            - name: Await Run ID ${{ steps.return_dispatch.outputs.run_id }}
              uses: Codex-/await-remote-run@v1.0.0
              with:
                token: ${{ github.token }}
                repo: year-long-project-team-3
                owner: COSC-499-W2023
                run_id: ${{ steps.return_dispatch.outputs.run_id }}
            - name: Checkout
              uses: actions/checkout@v4
            - name: Write cypress.env.json
              run: |
                  echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json
            - name: Write .env
              run: |
                  echo "${{ secrets.ENV_TEST_LOCAL }}" > .env
#            - name: Build and start the app
#              run: |
#                  npm install
#                  npm run build
#                  mkdir -p /home/runner/work/year-long-project-team-3/debugs
#                  npm run start >> /home/runner/work/year-long-project-team-3/debugs/output.txt 2>&1 &
            - name: Cypress Run Component Tests
              uses: cypress-io/github-action@v6
              env:
                CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
                CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
              with:
                  install: false
                  wait-on: ${{ secrets.BASE_URL }}
                  browser: chromium
                  config: baseUrl=${{ secrets.BASE_URL }}
                  component: true
                  record: true
            - name: Cypress Run E2E Tests
              uses: cypress-io/github-action@v6
              env:
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.PERSONAL_GITHUB_ACCESS_TOKEN }}
                  CYPRESS_BASE_URL: ${{ github.event.deployment_status.target_url }}
              with:
                  install: false
                  config: baseUrl=${{ secrets.BASE_URL }}
                  wait-on: ${{ secrets.BASE_URL }}
                  browser: chromium
                  record: true
                  parallel: true
#            - name: Save output.txt as artifact
#              uses: actions/upload-artifact@v2
#              if: failure()
#              with:
#                  name: output
#                  path: /home/runner/work/year-long-project-team-3/debugs/output.txt
#                  if-no-files-found: ignore
